addons:
  sonarcloud:
    organization: "dfalessi-github"
    token:
      secure: "6d5fccf5ce22996002f393e11bf4f4e3470adb81"
	  
jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
  
  